- hosts: all
  become: true
  tasks:
    # Actualizamos paquetes
    - name: Actualizamos el sistema
      apt:
        update_cache: yes
        upgrade: yes

    # Instalar paquetes git y apache2
    - name: "Instalar paquetes con apt"
      apt:
        name:
          - git
          - apache2
        state: present

    # Copia un fichero a la máquina remota
    - name: "Copiar fichero a la máquina remota"
      copy:
        src: files/foo.conf
        dest: /etc/foo.conf  # Ruta donde se guardará el archivo en la máquina remota
        owner: root
        group: root
        mode: '0644'

    # Copia un template a un fichero de la máquina remota
    - name: "Copiar un template a un fichero de la máquina remota"
      template:
        src: template/index.j2  # Ruta del template en la máquina local
        dest: /var/www/html/index.html  # Ruta donde se guardará el template en la máquina remota
        owner: www-data
        group: www-data
        mode: '0644'
