- name: ensure mariadb is installed
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: present
    update_cache: yes

- name: create database wordpress
  mysql_db: name={{nombre_base_datos}} state=present

- name: create user mysql wordpress
  mysql_user: name={{nombre_usuario}} host={{ item }} password={{mysql_password}} priv={{nombre_base_datos}}.*:ALL,GRANT
  with_items:
    - localhost

- name: mariadb listen in all interfaces
  lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf regexp="^bind-address            = 127.0.0.1" line="bind-address            = 0.0.0.0" state=present
  notify:
    - restart mariadb
